/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get deployment plan
         * @description Retrieve the current deployment plan with stages and SLOs
         */
        get: operations["getPlan"];
        put?: never;
        /**
         * Update deployment plan
         * @description Create or update the deployment plan configuration
         */
        post: operations["updatePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List releases
         * @description Get a list of all releases including current and completed ones
         */
        get: operations["listReleases"];
        put?: never;
        /**
         * Create release
         * @description Create a new release. Only one release can be staged at a time
         */
        post: operations["createRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/release/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get active release
         * @description Retrieve the active release
         */
        get: operations["getActiveRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/release/{releaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get release details
         * @description Retrieve release state, plan record, and stage information
         */
        get: operations["getRelease"];
        put?: never;
        /**
         * Control release execution
         * @description Start or stop a release. Only one release can be active at a time
         */
        post: operations["controlRelease"];
        /**
         * Delete release
         * @description Delete a release that is in 'not_started' state
         */
        delete: operations["deleteRelease"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/release/{releaseId}/stage/{releaseStageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get release stage status
         * @description Get the current state of a specific stage within a release
         */
        get: operations["getReleaseStage"];
        put?: never;
        /**
         * Progress release stage
         * @description Advance a stage if it is in the 'awaiting_approval' state
         */
        post: operations["progressReleaseStage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example {
         *       "order": 0,
         *       "target_percent": 25,
         *       "soak_time": 10,
         *       "auto_progress": true
         *     } */
        PlanStage: {
            /** @description order of the stage in the plan */
            order: number;
            description?: string;
            /** @description target percentage of traffic that goes to the new Worker version */
            target_percent: number;
            /** @description soak time in seconds */
            soak_time: number;
            /** @description whether the stage automatically progresses or if it needs a human to manually progress it */
            auto_progress: boolean;
        };
        /** @example {
         *       "id": "b2a2c3d4e5f6a1b2d3d5e5f6a1b2c3d5",
         *       "order": 0,
         *       "state": "queued",
         *       "time_started": "2023-01-01T00:00:00Z",
         *       "time_elapsed": 0
         *     } */
        ReleaseStage: {
            id: string;
            /** @description order of the stage in the release */
            order: number;
            /** @enum {string} */
            state: "queued" | "awaiting_approval" | "running" | "done_failed" | "done_successful";
            /** Format: date-time */
            time_started: string;
            time_elapsed: number;
            logs: string;
        };
        /** @example {
         *       "id": "b2a2c3d4e5f6a1b2d3d5e5f6a1b2c3d5",
         *       "state": "not_started",
         *       "plan_record": {
         *         "$ref": "#/components/schemas/Plan"
         *       },
         *       "stages": [
         *         {
         *           "$ref": "#/components/schemas/ReleaseStage"
         *         }
         *       ],
         *       "time_started": {
         *         "type": "string",
         *         "format": "date-time"
         *       },
         *       "time_elapsed": {
         *         "type": "integer"
         *       },
         *       "time_done": {
         *         "type": "string",
         *         "format": "date-time"
         *       }
         *     } */
        Release: {
            id: string;
            /** @enum {string} */
            state: "not_started" | "running" | "done_stopped_manually" | "done_failed_slo" | "done_successful";
            plan_record: components["schemas"]["Plan"];
            stages: components["schemas"]["ReleaseStage"][];
            /** Format: date-time */
            time_created: string;
            /** Format: date-time */
            time_started: string;
            time_elapsed: number;
            /** Format: date-time */
            time_done: string;
        };
        /** @example {
         *       "stages": [
         *         {
         *           "$ref": "#/components/schemas/PlanStage"
         *         }
         *       ],
         *       "slos": [
         *         {
         *           "$ref": "#/components/schemas/SLO"
         *         }
         *       ]
         *     } */
        Plan: {
            stages: components["schemas"]["PlanStage"][];
            slos: components["schemas"]["SLO"][];
            /** Format: date-time */
            readonly time_last_saved?: string;
        };
        /** @example {
         *       "value": "latency p99 100"
         *     } */
        SLO: {
            value: string;
        };
    };
    responses: never;
    parameters: {
        releaseStageId: string;
        releaseId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Plan not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Plan"];
            };
        };
        responses: {
            /** @description Plan updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Plan is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listReleases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of releases retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"][];
                };
            };
            /** @description No releases found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createRelease: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Release created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"];
                };
            };
            /** @description Release cannot be created from the plan */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A release is already staged */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getActiveRelease: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active release retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"];
                };
            };
            /** @description No active release found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["releaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Release details retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"];
                };
            };
            /** @description Release not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    controlRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["releaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/text": "start" | "stop";
            };
        };
        responses: {
            /** @description start or stop was successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provided command is not valid for the release in its current state */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Release not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["releaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Release deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Release not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Release has to be in a "not_started" state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getReleaseStage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["releaseId"];
                releaseStageId: components["parameters"]["releaseStageId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the Stage info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseStage"];
                };
            };
            /** @description Stage not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    progressReleaseStage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["releaseId"];
                releaseStageId: components["parameters"]["releaseStageId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/text": "approve" | "deny";
            };
        };
        responses: {
            /** @description Successfully progressed the stage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stage not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stage has to be in a "awaiting_approval" state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
